### ISSUE TITLE
Randomly, it errs when using /play-music

### ISSUE THREAD

**Issue by TheBookKnight** [JoshuaTheEngineer/Saint-Anonymous#10]
Sometimes, when you use the `/play-music` command, the bot crashes with the below log
```
node:events:504
      throw er; // Unhandled 'error' event
      ^

R [Error]: aborted
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketCloseListener (node:_http_client:402:19)
    at TLSSocket.emit (node:events:538:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
Emitted 'error' event on B instance at:
    at OggDemuxer.t (/Users/macpro/Documents/radical projects/Saint-Anonymous/node_modules/@discordjs/voice/dist/index.js:8:288)
    at Object.onceWrapper (node:events:646:26)
    at OggDemuxer.emit (node:events:538:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  resource: <ref *3> T {
    playStream: OggDemuxer {
      _readableState: ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList {
          head: { data: [Buffer [Uint8Array]], next: [Object] },
          tail: { data: [Buffer [Uint8Array]], next: null },
          length: 63
        },
        length: 63,
        pipes: [],
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        constructed: true,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        errorEmitted: true,
        emitClose: true,
        autoDestroy: true,
        destroyed: true,
        errored: Error: aborted
            at connResetException (node:internal/errors:691:14)
            at TLSSocket.socketCloseListener (node:_http_client:402:19)
            at TLSSocket.emit (node:events:538:35)
            at node:net:687:12
            at TCP.done (node:_tls_wrap:580:7) {
          code: 'ECONNRESET'
        },
        closed: true,
        closeEmitted: false,
        defaultEncoding: 'utf8',
        awaitDrainWriters: null,
        multiAwaitDrain: false,
        readingMore: false,
        dataEmitted: true,
        decoder: null,
        encoding: null,
        [Symbol(kPaused)]: null
      },
      _events: [Object: null prototype] {
        prefinish: [Function: prefinish],
        close: [ [Function (anonymous)], [Function: onclose] ],
        end: [Function: onend],
        finish: [Function: onfinish],
        error: [Function: onerror]
      },
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: true,
        ending: false,
        ended: false,
        finished: false,
        destroyed: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 20916,
        writing: true,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: [Function: nop],
        writelen: 8192,
        afterWriteTickInfo: null,
        buffered: [
          {
            chunk: [Buffer [Uint8Array]],
            encoding: 'buffer',
            callback: [Function: nop]
          },
          {
            chunk: [Buffer [Uint8Array]],
            encoding: 'buffer',
            callback: [Function: nop]
          }
        ],
        bufferedIndex: 0,
        allBuffers: true,
        allNoop: true,
        pendingcb: 3,
        constructed: true,
        prefinished: false,
        errorEmitted: true,
        emitClose: true,
        autoDestroy: true,
        errored: Error: aborted
            at connResetException (node:internal/errors:691:14)
            at TLSSocket.socketCloseListener (node:_http_client:402:19)
            at TLSSocket.emit (node:events:538:35)
            at node:net:687:12
            at TCP.done (node:_tls_wrap:580:7) {
          code: 'ECONNRESET'
        },
        closed: true,
        closeEmitted: false,
        [Symbol(kOnFinished)]: []
      },
      allowHalfOpen: true,
      _remainder: null,
      _head: null,
      _bitstream: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    edges: [
      <ref *1> {
        type: 'ffmpeg ogg',
        to: _e {
          edges: [ [Object], [Object], [Object] ],
          type: 'ogg/opus'
        },
        cost: 2,
        transformer: [Function: transformer],
        from: _e { edges: [ [Object], [Circular *1] ], type: 'arbitrary' }
      },
      <ref *2> {
        type: 'ogg/opus demuxer',
        to: _e { edges: [ [Object] ], type: 'opus' },
        cost: 1,
        transformer: [Function: transformer],
        from: _e {
          edges: [ [Circular *2], [Object], [Object] ],
          type: 'ogg/opus'
        }
      }
    ],
    metadata: null,
    volume: undefined,
    encoder: undefined,
    audioPlayer: <ref *4> B {
      _events: [Object: null prototype] { idle: [Function (anonymous)] },
      _eventsCount: 1,
      _maxListeners: undefined,
      _state: {
        status: 'playing',
        missedFrames: 0,
        playbackDuration: 63740,
        resource: [Circular *3],
        onStreamError: [Function: t]
      },
      subscribers: [
        O {
          connection: G {
            _events: [Object: null prototype] {},
            _eventsCount: 0,
            _maxListeners: undefined,
            rejoinAttempts: 0,
            _state: [Object],
            joinConfig: [Object],
            packets: [Object],
            receiver: [j],
            debug: null,
            onNetworkingClose: [Function: bound onNetworkingClose],
            onNetworkingStateChange: [Function: bound onNetworkingStateChange],
            onNetworkingError: [Function: bound onNetworkingError],
            onNetworkingDebug: [Function: bound onNetworkingDebug],
            [Symbol(kCapture)]: false
          },
          player: [Circular *4]
        }
      ],
      behaviors: { noSubscriber: 'pause', maxMissedFrames: 5 },
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    playbackDuration: 63740,
    started: true,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
```

**Comment by TheBookKnight** [comment]
The issue might be with the ytdl-core library. It's possible to avoid this via [this StackOverflow solution](https://stackoverflow.com/a/69230592). 

I may have to use [the play-dl package](https://www.npmjs.com/package/play-dl). 

Also, it's harder to reproduce if it's running as a Docker container

Warning: this solution has a few downloads.

**Comment by TheBookKnight** [comment]
Similar issues referenced here
https://github.com/fent/node-ytdl-core/issues/994
https://github.com/discordjs/voice/issues/116#issuecomment-860080796

Perhaps I should try this implementation
https://github.com/fent/node-ytdl-core/issues/994#issuecomment-906581288

**Comment by TheBookKnight** [comment]
Tried pulling one of the newer Node Docker images
`docker pull node:17.8.0-alpine3.15`

But, it triggered more errors
```
...
#10 34.81 npm ERR! code 1
#10 34.81 npm ERR! path /usr/src/bot/node_modules/@discordjs/opus
#10 34.81 npm ERR! command failed
#10 34.81 npm ERR! command sh -c node-pre-gyp install --fallback-to-build
#10 34.81 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2/opus.node --module_name=opus --module_path=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#10 34.81 npm ERR! node-pre-gyp info it worked if it ends with ok
#10 34.81 npm ERR! node-pre-gyp info using node-pre-gyp@0.4.2
#10 34.81 npm ERR! node-pre-gyp info using node@17.8.0 | linux | x64
#10 34.81 npm ERR! node-pre-gyp info check checked for "/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2/opus.node" (not found)
#10 34.81 npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-linux-x64-musl-1.2.2.tar.gz
#10 34.81 npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-linux-x64-musl-1.2.2.tar.gz 
#10 34.81 npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.7.0 and node@17.8.0 (node-v102 ABI, musl) (falling back to source compile with node-gyp) 
#10 34.81 npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-linux-x64-musl-1.2.2.tar.gz 
#10 34.81 npm ERR! gyp info it worked if it ends with ok
#10 34.81 npm ERR! gyp info using node-gyp@9.0.0
#10 34.81 npm ERR! gyp info using node@17.8.0 | linux | x64
#10 34.81 npm ERR! gyp info ok 
#10 34.81 npm ERR! gyp info it worked if it ends with ok
#10 34.81 npm ERR! gyp info using node-gyp@9.0.0
#10 34.81 npm ERR! gyp info using node@17.8.0 | linux | x64
#10 34.81 npm ERR! gyp ERR! find Python 
#10 34.81 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#10 34.81 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#10 34.81 npm ERR! gyp ERR! find Python checking if "python3" can be used
#10 34.81 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#10 34.81 npm ERR! gyp ERR! find Python checking if "python" can be used
#10 34.81 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#10 34.81 npm ERR! gyp ERR! find Python 
#10 34.81 npm ERR! gyp ERR! find Python **********************************************************
#10 34.81 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#10 34.81 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#10 34.81 npm ERR! gyp ERR! find Python you can try one of the following options:
#10 34.81 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#10 34.81 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#10 34.81 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#10 34.81 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#10 34.81 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#10 34.81 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#10 34.81 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#10 34.81 npm ERR! gyp ERR! find Python **********************************************************
#10 34.81 npm ERR! gyp ERR! find Python 
#10 34.81 npm ERR! gyp ERR! configure error 
#10 34.81 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#10 34.81 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#10 34.81 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#10 34.81 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#10 34.81 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#10 34.81 npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
#10 34.81 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#10 34.82 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
#10 34.82 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#10 34.82 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
#10 34.82 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#10 34.82 npm ERR! gyp ERR! System Linux 5.10.104-linuxkit
#10 34.82 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2/opus.node" "--module_name=opus" "--module_path=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#10 34.82 npm ERR! gyp ERR! cwd /usr/src/bot/node_modules/@discordjs/opus
#10 34.82 npm ERR! gyp ERR! node -v v17.8.0
#10 34.82 npm ERR! gyp ERR! node-gyp -v v9.0.0
#10 34.82 npm ERR! gyp ERR! not ok 
#10 34.82 npm ERR! node-pre-gyp ERR! build error 
#10 34.82 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2/opus.node --module_name=opus --module_path=/usr/src/bot/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-musl-1.2.2 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#10 34.82 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/bot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
#10 34.82 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
#10 34.82 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
#10 34.82 npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
#10 34.82 npm ERR! node-pre-gyp ERR! System Linux 5.10.104-linuxkit
#10 34.82 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#10 34.82 npm ERR! node-pre-gyp ERR! cwd /usr/src/bot/node_modules/@discordjs/opus
#10 34.82 npm ERR! node-pre-gyp ERR! node -v v17.8.0
#10 34.82 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.2
#10 34.82 npm ERR! node-pre-gyp ERR! not ok
#10 34.82 
#10 34.82 npm ERR! A complete log of this run can be found in:
#10 34.82 npm ERR!     /root/.npm/_logs/2022-04-02T05_13_56_839Z-debug-0.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
make: *** [build] Error 1

```

**Comment by TheBookKnight** [comment]
Issue possibly solved by 
https://github.com/JoshuaTheEngineer/Saint-Anonymous/pull/17 

Used Example from
https://github.com/play-dl/play-dl/blob/main/examples/YouTube/play%20-%20url.js
