### ISSUE TITLE
When the bot's disconnected but you /stop-music, the bot crashes

### ISSUE THREAD

**Issue by TheBookKnight** [JoshuaTheEngineer/Saint-Anonymous#14]
Steps to reproduce:
1. Saint Anonymous bot online
2. In any Text Channel, run /stop-music
3. Observe Saint Anonymous docker container

Error Log below
```
/usr/src/bot/commands/stop-music.js:10

                voice.getVoiceConnection(message.guildId).disconnect();

                                                         ^


TypeError: Cannot read properties of undefined (reading 'disconnect')

    at Object.execute (/usr/src/bot/commands/stop-music.js:10:58)

    at Object.execute (/usr/src/bot/events/interactionCreate.js:12:12)

    at Client.<anonymous> (/usr/src/bot/index.js:25:56)

    at Client.emit (node:events:526:28)

    at InteractionCreateAction.handle (/usr/src/bot/node_modules/discord.js/src/client/actions/InteractionCreate.js:74:12)

    at Object.module.exports [as INTERACTION_CREATE] (/usr/src/bot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)

    at WebSocketManager.handlePacket (/usr/src/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)

    at WebSocketShard.onPacket (/usr/src/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)

    at WebSocketShard.onMessage (/usr/src/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

    at WebSocket.onMessage (/usr/src/bot/node_modules/ws/lib/event-target.js:199:18)

ERROR: "start" exited with 1.
```

**Comment by TheBookKnight** [comment]
Fixes the bug
https://github.com/JoshuaTheEngineer/Saint-Anonymous/pull/15
